### ISSUE TITLE
Commit SigV4 auth addition to Envoy upstream

### ISSUE THREAD

**Issue by jamsajones** [awslabs/aws-app-mesh-examples#38]

**Comment by lavignes** [comment]
I've opened an issue regarding this in envoyproxy/envoy#5215. Currently exploring the feasibility of dropping the AWS SDK dependency.

**Comment by dio** [comment]
This will be pretty if we can do something like:

```
dynamic_resources:
  lds_config: {ads: {}}
  cds_config: {ads: {}}
  ads_config:
    api_type: GRPC
    grpc_services:
    - google_grpc:
        target_uri: xds.aws.com:443
        stat_prefix: xds_aws
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: XDS_SERVER_CERT
        call_credentials:
          aws_ec2: {}
```

The `aws_ec2` is similar to `google_compute_engine` which I believe is constructed here at https://github.com/grpc/grpc/blob/142acb3b0fd2b3586ad150691ddbe95a8bfdd73f/src/core/lib/security/credentials/oauth2/oauth2_credentials.cc#L378. Not sure if this is viable to do that by extending the `grpc::MetadataCredentialsPlugin`.

**Comment by lavignes** [comment]
@dio Yes. We are doing something pretty much exactly like that in our custom envoy build. Envoy provides an API for plugin credentials, so we're specifying our `aws_iam` extension for our credentials factory.

A bootstrap right now contains something like this:
```
dynamic_resources:
  lds_config: {ads: {}}
  cds_config: {ads: {}}
  ads_config:
    api_type: GRPC
    grpc_services:
      google_grpc:
        target_uri: appmesh-envoy-management.us-west-2.amazonaws.com:443
        stat_prefix: xds
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: /etc/pki/tls/cert.pem
        credentials_factory_name: envoy.grpc_credentials.aws_iam
        call_credentials:
          from_plugin:
            name: envoy.grpc_credentials.aws_iam
```
